#!/bin/bash
if [ "$1" == "" ] || [ "$1" == "-h" ] || [ "$1" == "--help" ]; then
        echo "./loganalyser.sh /path/file"
	echo "Находит 99 перцентиль по времени обработки запроса для log в file."
        exit 0
fi
if ! [ -f "$1" ]; then
        echo "File not exist"
        exit 9
fi
c=0
logInLines=()
while read -r line
do
parsedLogLine=()
read -ra parsedLogLine <<< $line
index=$(( ${#parsedLogLine[@]} - 1 ))
logInLines+=( "${parsedLogLine[$index]}" )
c=$((c+1))
echo $c/10000000
done < "$1"
c=0
for ((i = 0; i<${#logInLines[@]}; i++)) 
do
      
    for((j = i; j<${#logInLines[@]}-i-1; j++)) 
    do
      
        if ((${logInLines[j]} > ${logInLines[$((j+1))]})) 
        then
            temp=${logInLines[$j]} 
            logInLines[$j]=${logInLines[$((j+1))]}   
            logInLines[$((j+1))]=$temp 
        fi
    done
   echo $c out of 10000000
done
for qi in "${logInLines[@]}"
do
echo $qi
done
rang=${#logInLines[@]}
percentilNumber=$(( rang*99 ))
percentilNumberMod=$(( percentilNumber%100 ))
percentilNumber=$(( percentilNumber/100 ))
if [ $percentilNumberMod -gt 0 ]; then
percentilNumber=$(( percentilNumber + 1 ))
fi
echo ${logInLines[$(( percentilNumber - 1 ))]}
